// Config generation for the platform adapter surface: per-agent
// configuration fragments that route hook callbacks into the receiver
// subcommand of this binary.
//
// Supported targets (three faces, deliberately different shapes):
//
//   - claude-code: merge a hooks block into the agent's settings.json.
//     The generated block registers a plain command hook only. It
//     carries NO decision vocabulary of any kind — there is nothing in
//     the generated bytes that could instruct the agent to accept or
//     refuse a tool call (Phase 0 records only).
//   - codex: no public hook event face exists, so the generator writes
//     NOTHING for this target and reports the coverage honestly as a
//     process-observation known gap (the long-running collector still
//     sees codex processes; that is OS-level coverage, not hooks).
//   - openclaw: first-party target; merge an "agentRuntime" block into
//     openclaw.json recording which events the collector wants mirrored.
//     The block shape is our own product's contract, not an upstream
//     standard, and is documented as such.
//
// All merges are idempotent (second run changes nothing) and fail
// closed on unparseable existing user config (never overwrite bytes the
// generator cannot prove it understands).
package adapter

import (
	"encoding/json"
	"errors"
	"fmt"
	"sort"
)

// CodexGap is the honest coverage note for the codex face. It is
// printed by the generator instead of writing any configuration.
const CodexGap = "codex: no public hook event face is available to register; " +
	"process observation (agent detection + OS-level audit) covers it instead. " +
	"Known gap recorded: hook-level tool events for codex are not captured. " +
	"No configuration written."

// HookEventNames lists the agent-facing event face the receiver
// understands, in stable order (generator output and gate assertions
// both key off this list).
func HookEventNames() []string {
	return []string{EventPreToolUse, EventPostToolUse, EventSessionStart, EventStop}
}

// toolFaceEvents are the events that carry a tool matcher; the session
// face events do not.
func isToolEvent(name string) bool {
	return name == EventPreToolUse || name == EventPostToolUse
}

// receiverCommand builds the exact command line written into generated
// configuration: the receiver binary plus its subcommand, nothing else.
func receiverCommand(bin string) string {
	return bin + " hook"
}

// ClaudeHooksBlock renders the hooks value for Claude-Code-shaped
// settings: one matcher group per event face, each holding a single
// recording command. Pure function of the binary path (deterministic
// output for the fixture diff assertions).
func ClaudeHooksBlock(bin string) map[string]any {
	hooks := map[string]any{}
	names := HookEventNames()
	sort.Strings(names)
	for _, ev := range names {
		group := map[string]any{
			"hooks": []any{
				map[string]any{"type": "command", "command": receiverCommand(bin)},
			},
		}
		if isToolEvent(ev) {
			group["matcher"] = ".*"
		}
		hooks[ev] = []any{group}
	}
	return hooks
}

// MergeClaudeSettings inserts (or refreshes) the recorder hooks inside a
// settings.json document. existing may be empty (new file). Returns the
// new bytes and whether anything changed. Rules:
//   - invalid existing JSON => error, changed=false (fail closed);
//   - an entry whose command is exactly the receiver command is treated
//     as already-present (idempotence); foreign entries are preserved
//     byte-for-value untouched;
//   - unrelated top-level keys are never modified.
func MergeClaudeSettings(existing []byte, bin string) ([]byte, bool, error) {
	doc := map[string]any{}
	if len(existing) > 0 {
		if err := json.Unmarshal(existing, &doc); err != nil {
			return nil, false, fmt.Errorf("adapter: existing settings json unparseable, refusing to overwrite: %w", err)
		}
	}
	want := ClaudeHooksBlock(bin)
	hooks, _ := doc["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
	}
	changed := false
	for ev, groups := range want {
		arr, _ := hooks[ev].([]any)
		if containsReceiver(arr, receiverCommand(bin)) {
			continue // already wired: keep user's exact arrangement
		}
		gs, ok := groups.([]any)
		if !ok || len(gs) != 1 {
			return nil, false, errors.New("adapter: internal block shape unexpected")
		}
		arr = append(arr, gs[0])
		hooks[ev] = arr
		changed = true
	}
	if !changed {
		return existing, false, nil
	}
	doc["hooks"] = hooks
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, false, err
	}
	return append(out, '\n'), true, nil
}

func containsReceiver(groups []any, cmd string) bool {
	for _, g := range groups {
		gm, ok := g.(map[string]any)
		if !ok {
			continue
		}
		hl, _ := gm["hooks"].([]any)
		for _, h := range hl {
			hm, ok := h.(map[string]any)
			if !ok {
				continue
			}
			if hm["command"] == cmd {
				return true
			}
		}
	}
	return false
}

// OpenClawBlock renders the first-party "agentRuntime" block for the
// openclaw.json surface. Like the Claude block it carries zero decision
// vocabulary: it only states which events should be mirrored to the
// receiver command.
func OpenClawBlock(bin string) map[string]any {
	return map[string]any{
		"collectorBin": bin,
		"mode":         "observe",
		"events":       HookEventNames(),
	}
}

// MergeOpenClaw inserts (or refreshes) the agentRuntime block inside an
// openclaw.json document with the same fail-closed/idempotence rules as
// MergeClaudeSettings.
func MergeOpenClaw(existing []byte, bin string) ([]byte, bool, error) {
	doc := map[string]any{}
	if len(existing) > 0 {
		if err := json.Unmarshal(existing, &doc); err != nil {
			return nil, false, fmt.Errorf("adapter: existing openclaw json unparseable, refusing to overwrite: %w", err)
		}
	}
	want := OpenClawBlock(bin)
	if cur, ok := doc["agentRuntime"].(map[string]any); ok && sameBlock(cur, want) {
		return existing, false, nil
	}
	doc["agentRuntime"] = want
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, false, err
	}
	return append(out, '\n'), true, nil
}

func sameBlock(a, b map[string]any) bool {
	ja, _ := json.Marshal(a)
	jb, _ := json.Marshal(b)
	return string(ja) == string(jb)
}
