package adapter

import (
	"encoding/json"
	"strings"
	"testing"
)

func decode(t *testing.T, b []byte) map[string]any {
	t.Helper()
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		t.Fatalf("generated config invalid json: %v\n%s", err, b)
	}
	return m
}

func TestMergeClaudeSettingsFresh(t *testing.T) {
	out, changed, err := MergeClaudeSettings(nil, "/opt/rt/agent-collector")
	if err != nil || !changed {
		t.Fatalf("fresh merge: %v %v", err, changed)
	}
	doc := decode(t, out)
	hooks, ok := doc["hooks"].(map[string]any)
	if !ok {
		t.Fatal("no hooks key")
	}
	for _, ev := range HookEventNames() {
		groups, ok := hooks[ev].([]any)
		if !ok || len(groups) != 1 {
			t.Fatalf("event %s missing/odd: %v", ev, hooks[ev])
		}
		g := groups[0].(map[string]any)
		hl := g["hooks"].([]any)
		cmd := hl[0].(map[string]any)["command"]
		if cmd != "/opt/rt/agent-collector hook" {
			t.Errorf("%s command: %v", ev, cmd)
		}
		if (isToolEvent(ev)) != (g["matcher"] == ".*") {
			t.Errorf("%s matcher presence mismatch: %v", ev, g["matcher"])
		}
	}
	// Phase 0 structural assertion: the generated bytes carry no
	// decision vocabulary of any kind.
	s := string(out)
	for _, w := range []string{"deny", "permissionDecision", "\"ask\"", "block"} {
		if strings.Contains(s, w) {
			t.Errorf("generated config carries decision word %q", w)
		}
	}
}

func TestMergeClaudeSettingsPreservesAndIdempotent(t *testing.T) {
	existing := []byte(`{
  "model": "somemodel",
  "permissions": {"allow": ["Bash(git status)"]},
  "hooks": {"PreToolUse": [{"matcher": "Edit", "hooks": [{"type": "command", "command": "/usr/bin/other"}]}]}
}`)
	out, changed, err := MergeClaudeSettings(existing, "/bin/ac")
	if err != nil || !changed {
		t.Fatalf("merge: %v %v", err, changed)
	}
	doc := decode(t, out)
	if doc["model"] != "somemodel" {
		t.Error("unrelated key lost")
	}
	pre := doc["hooks"].(map[string]any)["PreToolUse"].([]any)
	if len(pre) != 2 {
		t.Fatalf("user group lost or duplicated: %d", len(pre))
	}
	first := pre[0].(map[string]any)
	if first["matcher"] != "Edit" {
		t.Error("user matcher mutated")
	}
	// second run: nothing changes (idempotence)
	out2, changed2, err := MergeClaudeSettings(out, "/bin/ac")
	if err != nil {
		t.Fatal(err)
	}
	if changed2 || string(out2) != string(out) {
		t.Error("merge not idempotent")
	}
}

func TestMergeClaudeSettingsFailClosedOnGarbage(t *testing.T) {
	out, changed, err := MergeClaudeSettings([]byte("{ broken json"), "/bin/ac")
	if err == nil || changed {
		t.Fatalf("must refuse to overwrite unparseable config: %v %v", err, changed)
	}
	if out != nil {
		t.Error("must return no bytes on refusal")
	}
}

func TestMergeOpenClaw(t *testing.T) {
	out, changed, err := MergeOpenClaw([]byte(`{"theme":"dark"}`), "/bin/ac")
	if err != nil || !changed {
		t.Fatalf("openclaw merge: %v %v", err, changed)
	}
	doc := decode(t, out)
	if doc["theme"] != "dark" {
		t.Error("existing key lost")
	}
	blk, ok := doc["agentRuntime"].(map[string]any)
	if !ok {
		t.Fatal("agentRuntime missing")
	}
	if blk["mode"] != "observe" || blk["collectorBin"] != "/bin/ac" {
		t.Errorf("block shape: %v", blk)
	}
	evs, _ := blk["events"].([]any)
	if len(evs) != len(HookEventNames()) {
		t.Errorf("event face: %v", blk["events"])
	}
	if _, ch2, err := MergeOpenClaw(out, "/bin/ac"); err != nil || ch2 {
		t.Error("openclaw merge not idempotent")
	}
	for _, w := range []string{"deny", "block"} {
		if strings.Contains(strings.ToLower(string(out)), w) {
			t.Errorf("openclaw config carries %q", w)
		}
	}
}

func TestCodexGapNoteHonestAndEmptyWrites(t *testing.T) {
	if !strings.Contains(CodexGap, "No configuration written") {
		t.Error("gap note must state the zero-write outcome")
	}
	if !strings.Contains(strings.ToLower(CodexGap), "known gap") {
		t.Error("gap note must record known_gap wording")
	}
}
